import {
  User, Post, Comment, Job, Conversation, Message,
  Notification, Experience, Education, Skill, Certification, NewsItem
} from "@/types";

export const currentUser: User = {
  id: "u1",
  name: "Alexandra Chen",
  headline: "Senior Software Engineer at Google | Full-Stack Developer | Tech Lead",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
  coverImage: "/src/assets/cover-banner.jpg",
  location: "San Francisco Bay Area",
  connectionCount: 1847,
  followerCount: 12500,
  followingCount: 342,
  isConnected: false,
  isFollowing: false,
  isPremium: true,
  isVerified: true,
  isOnline: true,
  profileViews: 284,
  postImpressions: 14230,
  email: "alex.chen@gmail.com",
  about: "Passionate software engineer with 8+ years of experience building scalable systems. I love turning complex problems into elegant solutions. Currently leading the infrastructure team at Google, focusing on distributed systems and cloud architecture.",
};

export const mockUsers: User[] = [
  {
    id: "u2",
    name: "Marcus Johnson",
    headline: "Product Manager at Meta | Building the Future of Social",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=200&fit=crop",
    location: "New York, NY",
    connectionCount: 2341,
    followerCount: 8900,
    followingCount: 215,
    isConnected: true,
    isFollowing: true,
    isPremium: true,
    isVerified: true,
    isOnline: true,
    profileViews: 542,
    postImpressions: 23400,
    email: "marcus.j@gmail.com",
  },
  {
    id: "u3",
    name: "Sarah Williams",
    headline: "UX Designer at Apple | Design Thinking Advocate",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    coverImage: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=200&fit=crop",
    location: "Cupertino, CA",
    connectionCount: 976,
    followerCount: 5400,
    followingCount: 189,
    isConnected: false,
    isFollowing: false,
    isPremium: false,
    isVerified: false,
    isOnline: false,
    profileViews: 189,
    postImpressions: 7800,
    email: "sarah.w@apple.com",
  },
  {
    id: "u4",
    name: "David Park",
    headline: "Data Scientist at Netflix | ML Engineer | Kaggle Grandmaster",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    coverImage: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=200&fit=crop",
    location: "Los Angeles, CA",
    connectionCount: 1234,
    followerCount: 18700,
    followingCount: 456,
    isConnected: true,
    isFollowing: false,
    isPremium: true,
    isVerified: false,
    isOnline: true,
    profileViews: 891,
    postImpressions: 45600,
    email: "david.p@netflix.com",
  },
  {
    id: "u5",
    name: "Emily Rodriguez",
    headline: "Startup Founder | CEO at TechVentures | Forbes 30 Under 30",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    coverImage: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=200&fit=crop",
    location: "Austin, TX",
    connectionCount: 5621,
    followerCount: 45200,
    followingCount: 128,
    isConnected: false,
    isFollowing: true,
    isPremium: true,
    isVerified: true,
    isOnline: false,
    profileViews: 3421,
    postImpressions: 128000,
    email: "emily.r@techventures.com",
  },
  {
    id: "u6",
    name: "James Liu",
    headline: "DevOps Engineer at Amazon | Cloud Architecture | AWS Certified",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    location: "Seattle, WA",
    connectionCount: 678,
    followerCount: 2300,
    followingCount: 89,
    isConnected: false,
    isFollowing: false,
    isPremium: false,
    isVerified: false,
    isOnline: true,
    profileViews: 134,
    postImpressions: 3400,
    email: "james.l@amazon.com",
  },
];

export const mockPosts: Post[] = [
  {
    id: "p1",
    author: mockUsers[0],
    content: `🚀 Excited to share that I just shipped a major feature at Meta that will impact millions of users!\n\nAfter 6 months of planning, building, and iterating, we launched our new AI-powered content recommendation system. Here's what I learned:\n\n1️⃣ Always start with the user problem, not the solution\n2️⃣ Data-driven decisions > gut feelings\n3️⃣ Cross-functional collaboration is everything\n4️⃣ Ship fast, learn faster\n\nThe feature increased user engagement by 34% in the first week. Incredibly proud of our team! 🙌\n\n#ProductManagement #Meta #AI #TechLeadership #Innovation`,
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
    ],
    timestamp: "2 hours ago",
    likes: 1847,
    comments: 234,
    reposts: 156,
    isLiked: false,
    isReposted: false,
    isSaved: false,
    reactions: { like: 1200, celebrate: 400, support: 100, love: 87, insightful: 60, funny: 0 },
    topReactions: ["👍", "🎉", "💙"],
    hashtags: ["ProductManagement", "Meta", "AI", "TechLeadership"],
  },
  {
    id: "p2",
    author: mockUsers[2],
    content: `Just finished reading "Don't Make Me Think" for the 3rd time and I still find new insights every read.\n\nHere are my top 5 UX principles that every designer (and developer!) should know:\n\n• Users don't read, they scan\n• Every page should have one clear primary action\n• Remove unnecessary words, then remove half of what's left\n• Users should never feel stupid\n• Accessibility is not optional — it's mandatory\n\nWhat's your most important UX principle? Drop it in the comments! 👇\n\n#UXDesign #ProductDesign #Apple #UserExperience`,
    images: [
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&h=400&fit=crop",
    ],
    timestamp: "5 hours ago",
    likes: 923,
    comments: 178,
    reposts: 89,
    isLiked: true,
    isReposted: false,
    isSaved: true,
    reactions: { like: 600, celebrate: 150, support: 80, love: 93, insightful: 0, funny: 0 },
    topReactions: ["👍", "💙", "🎉"],
    hashtags: ["UXDesign", "ProductDesign", "UserExperience"],
  },
  {
    id: "p3",
    author: mockUsers[3],
    content: `The AI landscape in 2026 is wild. 🤯\n\nI've been tracking ML model performance benchmarks for 3 years, and the progress is staggering:\n\n📈 GPT: 2020 → 2026 performance improvement: 47x\n📈 Image generation quality: nearly indistinguishable from real photos\n📈 Code generation: now handles 80% of boilerplate tasks autonomously\n\nBut here's the uncomfortable truth nobody talks about: we still don't fully understand WHY these models work.\n\nInterpretability is the next frontier. The team doing the most interesting work in this space right now is @AnthropicAI.\n\nWhat aspect of AI development keeps you up at night? 🤔`,
    timestamp: "8 hours ago",
    likes: 3241,
    comments: 456,
    reposts: 312,
    isLiked: false,
    isReposted: true,
    isSaved: false,
    reactions: { like: 2100, celebrate: 400, support: 200, love: 150, insightful: 391, funny: 0 },
    topReactions: ["👍", "💡", "🎉"],
    hashtags: ["AI", "MachineLearning", "DataScience", "Future"],
  },
  {
    id: "p4",
    author: mockUsers[4],
    content: `We just closed our Series B! 🎉 $45M raised to build the future of developer productivity.\n\nWhen I started TechVentures 3 years ago from my garage with $2,000 in savings, this felt like a dream. Today, with 50+ employees and 10,000+ customers, it's real.\n\nLessons from the fundraising journey:\n\n✅ Tell a clear story about WHY you exist\n✅ Know your metrics cold\n✅ Build relationships before you need them\n✅ Rejection is data, not failure\n\nThank you to every customer, employee, and advisor who believed in us. We're just getting started.\n\n#Startup #Fundraising #Entrepreneurship #TechStartup`,
    images: [
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&h=400&fit=crop",
    ],
    timestamp: "1 day ago",
    likes: 12450,
    comments: 892,
    reposts: 1234,
    isLiked: true,
    isReposted: false,
    isSaved: true,
    reactions: { like: 8000, celebrate: 3000, support: 800, love: 500, insightful: 150, funny: 0 },
    topReactions: ["🎉", "👍", "💙"],
    hashtags: ["Startup", "Fundraising", "Entrepreneurship"],
  },
  {
    id: "p5",
    author: currentUser,
    content: `Just gave a talk at Google I/O 2026 on "Building for Scale: Lessons from 10 Billion Requests/Day" 🎤\n\nKey takeaways I shared:\n\n1. Observability first — if you can't measure it, you can't fix it\n2. Design for failure, not success\n3. The strangler fig pattern is underrated for legacy migration\n4. Team culture determines system architecture (Conway's Law is real)\n\nFull talk recording is now available on YouTube. Link in the comments!\n\n#GoogleIO #SoftwareEngineering #SystemDesign #DistributedSystems`,
    images: [
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=600&h=400&fit=crop",
    ],
    timestamp: "2 days ago",
    likes: 4521,
    comments: 312,
    reposts: 567,
    isLiked: false,
    isReposted: false,
    isSaved: false,
    reactions: { like: 3000, celebrate: 900, support: 300, love: 200, insightful: 121, funny: 0 },
    topReactions: ["👍", "🎉", "💡"],
    hashtags: ["GoogleIO", "SoftwareEngineering", "SystemDesign"],
  },
];

export const mockComments: Comment[] = [
  {
    id: "c1",
    author: mockUsers[1],
    content: "This is absolutely incredible! Congratulations to you and the whole team. The 34% engagement increase speaks for itself! 🔥",
    timestamp: "1 hour ago",
    likes: 47,
    isLiked: false,
    replies: [
      {
        id: "c1r1",
        author: mockUsers[0],
        content: "Thanks Sarah! The team really crushed it. Design was a huge part of the success!",
        timestamp: "45 min ago",
        likes: 12,
        isLiked: true,
      },
    ],
  },
  {
    id: "c2",
    author: mockUsers[3],
    content: "Great insights! Cross-functional collaboration is truly the secret sauce. We saw similar patterns at Netflix. Would love to grab coffee and exchange notes!",
    timestamp: "2 hours ago",
    likes: 28,
    isLiked: true,
  },
  {
    id: "c3",
    author: currentUser,
    content: "Inspiring work! The data-driven approach combined with user empathy is the winning formula. Sharing this with my team immediately.",
    timestamp: "2 hours ago",
    likes: 15,
    isLiked: false,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    title: "Senior Frontend Engineer",
    company: "Stripe",
    companyLogo: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=50&h=50&fit=crop",
    location: "San Francisco, CA • Hybrid",
    type: "Full-time",
    salary: "$180,000 - $250,000/yr",
    description: "Join Stripe's frontend team to build the financial infrastructure of the internet. Work with React, TypeScript, and modern web technologies at massive scale.",
    skills: ["React", "TypeScript", "GraphQL", "Node.js", "CSS"],
    applicants: 347,
    postedDate: "2 days ago",
    isEasyApply: true,
    isSaved: false,
    isNew: true,
    matchScore: 92,
  },
  {
    id: "j2",
    title: "Staff Software Engineer - Platform",
    company: "Figma",
    companyLogo: "https://images.unsplash.com/photo-1614332287897-cdc485fa562d?w=50&h=50&fit=crop",
    location: "New York, NY • Remote",
    type: "Remote",
    salary: "$220,000 - $280,000/yr",
    description: "Help build Figma's collaborative platform used by millions of designers and developers. Focus on real-time collaboration, performance, and developer experience.",
    skills: ["TypeScript", "WebSockets", "React", "Rust", "WebAssembly"],
    applicants: 589,
    postedDate: "1 week ago",
    isEasyApply: false,
    isSaved: true,
    matchScore: 88,
  },
  {
    id: "j3",
    title: "Engineering Manager - Growth",
    company: "Airbnb",
    companyLogo: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=50&h=50&fit=crop",
    location: "San Francisco, CA • On-site",
    type: "Full-time",
    salary: "$250,000 - $320,000/yr",
    description: "Lead a team of 8 engineers building Airbnb's growth products. Drive experimentation culture, mentor senior engineers, and ship impactful product changes.",
    skills: ["Engineering Management", "A/B Testing", "Growth", "React", "Python"],
    applicants: 234,
    postedDate: "3 days ago",
    isEasyApply: true,
    isSaved: false,
    isNew: true,
    matchScore: 76,
  },
  {
    id: "j4",
    title: "Principal Engineer - Infrastructure",
    company: "Databricks",
    companyLogo: "https://images.unsplash.com/photo-1618477247222-acbaa0df4553?w=50&h=50&fit=crop",
    location: "Seattle, WA • Hybrid",
    type: "Full-time",
    salary: "$300,000 - $400,000+/yr",
    description: "Shape the technical direction of Databricks' data infrastructure platform. Drive architecture decisions for systems processing petabytes of data daily.",
    skills: ["Distributed Systems", "Spark", "Kubernetes", "Scala", "Go"],
    applicants: 145,
    postedDate: "5 days ago",
    isEasyApply: false,
    isSaved: false,
    matchScore: 84,
  },
  {
    id: "j5",
    title: "Senior Product Designer",
    company: "Linear",
    companyLogo: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=50&h=50&fit=crop",
    location: "Remote",
    type: "Remote",
    salary: "$160,000 - $200,000/yr",
    description: "Design the best project management tool for software teams. Work closely with engineering and product to ship beautiful, functional experiences.",
    skills: ["Figma", "UI/UX Design", "Design Systems", "Prototyping"],
    applicants: 412,
    postedDate: "1 day ago",
    isEasyApply: true,
    isSaved: true,
    isNew: true,
    matchScore: 71,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv1",
    participant: mockUsers[0],
    lastMessage: {
      id: "m1",
      senderId: "u2",
      content: "That sounds great! Let's schedule a call for next week to discuss the collaboration.",
      timestamp: "2m ago",
      isRead: false,
      type: "text",
    },
    unreadCount: 3,
    isOnline: true,
    isPinned: true,
  },
  {
    id: "conv2",
    participant: mockUsers[2],
    lastMessage: {
      id: "m2",
      senderId: "u3",
      content: "I loved your talk at Google I/O! The distributed systems section was 🔥",
      timestamp: "1h ago",
      isRead: true,
      type: "text",
    },
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "conv3",
    participant: mockUsers[3],
    lastMessage: {
      id: "m3",
      senderId: "u1",
      content: "Hey! Can we connect? I'm interested in your work on ML interpretability.",
      timestamp: "3h ago",
      isRead: true,
      type: "text",
    },
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: "conv4",
    participant: mockUsers[4],
    lastMessage: {
      id: "m4",
      senderId: "u5",
      content: "Congratulations on the Series B! We should talk about potential integration opportunities.",
      timestamp: "Yesterday",
      isRead: true,
      type: "text",
    },
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "conv5",
    participant: mockUsers[1],
    lastMessage: {
      id: "m5",
      senderId: "u6",
      content: "Thanks for the AWS tips! Really helped with our migration.",
      timestamp: "2d ago",
      isRead: true,
      type: "text",
    },
    unreadCount: 0,
    isOnline: true,
  },
];

export const mockMessages: Message[] = [
  {
    id: "msg1",
    senderId: "u2",
    content: "Hey Alexandra! I saw your talk at Google I/O — absolutely brilliant work on distributed systems!",
    timestamp: "Yesterday 2:34 PM",
    isRead: true,
    type: "text",
  },
  {
    id: "msg2",
    senderId: "u1",
    content: "Thank you Marcus! It was a lot of fun to present. The audience had some great questions!",
    timestamp: "Yesterday 2:41 PM",
    isRead: true,
    type: "text",
  },
  {
    id: "msg3",
    senderId: "u2",
    content: "I wanted to reach out about a potential collaboration between our teams. We're building an AI feature that could benefit from your infrastructure expertise.",
    timestamp: "Yesterday 3:15 PM",
    isRead: true,
    type: "text",
  },
  {
    id: "msg4",
    senderId: "u1",
    content: "That sounds really interesting! What's the scope of the project? I'd love to learn more.",
    timestamp: "Yesterday 4:02 PM",
    isRead: true,
    type: "text",
  },
  {
    id: "msg5",
    senderId: "u2",
    content: "We're building a real-time recommendation system that needs to serve 100M+ users with sub-50ms latency. I think your expertise in distributed systems would be invaluable.",
    timestamp: "Yesterday 4:18 PM",
    isRead: true,
    type: "text",
  },
  {
    id: "msg6",
    senderId: "u1",
    content: "That's exactly the type of challenge I love! I've worked on similar scale at Google. We achieved 47ms P99 latency with a combination of edge caching and async processing.",
    timestamp: "Yesterday 4:35 PM",
    isRead: true,
    type: "text",
  },
  {
    id: "msg7",
    senderId: "u2",
    content: "That sounds great! Let's schedule a call for next week to discuss the collaboration.",
    timestamp: "2m ago",
    isRead: false,
    type: "text",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "connection",
    actor: mockUsers[4],
    content: "Emily Rodriguez accepted your connection request",
    timestamp: "5 minutes ago",
    isRead: false,
    actionUrl: "/profile/u5",
  },
  {
    id: "n2",
    type: "like",
    actor: mockUsers[0],
    content: "Marcus Johnson and 47 others liked your post about Google I/O",
    timestamp: "1 hour ago",
    isRead: false,
    postPreview: "Just gave a talk at Google I/O 2026 on Building for Scale...",
  },
  {
    id: "n3",
    type: "comment",
    actor: mockUsers[2],
    content: "Sarah Williams commented on your post",
    timestamp: "2 hours ago",
    isRead: false,
    postPreview: "Really insightful! The observability-first approach is game-changing.",
  },
  {
    id: "n4",
    type: "job",
    actor: { ...currentUser, name: "LinkedIn Jobs" },
    content: "New job match: Principal Engineer at Databricks — 84% match",
    timestamp: "3 hours ago",
    isRead: false,
  },
  {
    id: "n5",
    type: "birthday",
    actor: mockUsers[1],
    content: "Today is David Park's birthday! Send him a message",
    timestamp: "4 hours ago",
    isRead: true,
  },
  {
    id: "n6",
    type: "anniversary",
    actor: mockUsers[0],
    content: "Marcus Johnson is celebrating 3 years at Meta",
    timestamp: "5 hours ago",
    isRead: true,
  },
  {
    id: "n7",
    type: "mention",
    actor: mockUsers[3],
    content: "David Park mentioned you in a comment",
    timestamp: "6 hours ago",
    isRead: true,
    postPreview: "@AlexandraChen would have great insights on this architecture problem!",
  },
  {
    id: "n8",
    type: "repost",
    actor: mockUsers[4],
    content: "Emily Rodriguez reposted your article",
    timestamp: "1 day ago",
    isRead: true,
  },
  {
    id: "n9",
    type: "connection",
    actor: mockUsers[5] || mockUsers[1],
    content: "James Liu wants to connect with you",
    timestamp: "1 day ago",
    isRead: true,
  },
];

export const mockExperiences: Experience[] = [
  {
    id: "e1",
    title: "Senior Software Engineer",
    company: "Google",
    companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=50&h=50&fit=crop",
    location: "Mountain View, CA",
    startDate: "Jan 2021",
    current: true,
    description: "Leading the infrastructure platform team building distributed systems that serve 10B+ requests/day. Designed and implemented a new caching layer that reduced P99 latency by 40%.",
    skills: ["Go", "Kubernetes", "Distributed Systems", "gRPC", "BigQuery"],
  },
  {
    id: "e2",
    title: "Software Engineer II",
    company: "Uber",
    companyLogo: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=50&h=50&fit=crop",
    location: "San Francisco, CA",
    startDate: "Mar 2018",
    endDate: "Dec 2020",
    current: false,
    description: "Built real-time pricing and dispatch systems for Uber Eats, handling 50M+ daily active users. Migrated legacy monolith to microservices architecture.",
    skills: ["Python", "Java", "Kafka", "MySQL", "AWS"],
  },
  {
    id: "e3",
    title: "Junior Software Engineer",
    company: "Dropbox",
    companyLogo: "https://images.unsplash.com/photo-1511551203524-9a24350a5771?w=50&h=50&fit=crop",
    location: "San Francisco, CA",
    startDate: "Jun 2016",
    endDate: "Feb 2018",
    current: false,
    description: "Worked on the sync engine and API platform. Implemented key features for the Business tier including advanced sharing permissions and admin controls.",
    skills: ["Python", "React", "MySQL", "Redis"],
  },
];

export const mockEducation: Education[] = [
  {
    id: "ed1",
    school: "Stanford University",
    schoolLogo: "https://images.unsplash.com/photo-1562774053-701939374585?w=50&h=50&fit=crop",
    degree: "Master of Science",
    field: "Computer Science",
    startYear: "2014",
    endYear: "2016",
    grade: "4.0 GPA",
    activities: "Teaching Assistant for CS229 (Machine Learning). Research in distributed systems lab.",
  },
  {
    id: "ed2",
    school: "UC Berkeley",
    schoolLogo: "https://images.unsplash.com/photo-1607990283143-e81e7a2c9349?w=50&h=50&fit=crop",
    degree: "Bachelor of Science",
    field: "Electrical Engineering & Computer Science",
    startYear: "2010",
    endYear: "2014",
    grade: "3.9 GPA",
    activities: "President of Women in Computing club. Hackathon organizing committee.",
  },
];

export const mockSkills: Skill[] = [
  { id: "s1", name: "Distributed Systems", endorsements: 89, endorsed: false, category: "Top" },
  { id: "s2", name: "System Design", endorsements: 76, endorsed: true, category: "Top" },
  { id: "s3", name: "Go", endorsements: 64, endorsed: false, category: "Top" },
  { id: "s4", name: "Kubernetes", endorsements: 58, endorsed: true, category: "Industry" },
  { id: "s5", name: "Python", endorsements: 52, endorsed: false, category: "Industry" },
  { id: "s6", name: "React", endorsements: 47, endorsed: false, category: "Industry" },
  { id: "s7", name: "TypeScript", endorsements: 43, endorsed: false, category: "Industry" },
  { id: "s8", name: "AWS", endorsements: 38, endorsed: false, category: "Industry" },
  { id: "s9", name: "Machine Learning", endorsements: 31, endorsed: false, category: "Other" },
  { id: "s10", name: "Technical Leadership", endorsements: 28, endorsed: false, category: "Other" },
];

export const mockCertifications: Certification[] = [
  {
    id: "cert1",
    name: "Google Cloud Professional Cloud Architect",
    issuer: "Google",
    issuerLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=40&h=40&fit=crop",
    issueDate: "Mar 2024",
    expiryDate: "Mar 2026",
    credentialId: "GCP-PCA-2024-AC",
  },
  {
    id: "cert2",
    name: "AWS Solutions Architect — Professional",
    issuer: "Amazon Web Services",
    issuerLogo: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=40&h=40&fit=crop",
    issueDate: "Nov 2023",
    credentialId: "AWS-SAP-2023-AC",
  },
  {
    id: "cert3",
    name: "Certified Kubernetes Administrator (CKA)",
    issuer: "Cloud Native Computing Foundation",
    issuerLogo: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=40&h=40&fit=crop",
    issueDate: "Jul 2023",
    expiryDate: "Jul 2026",
  },
];

export const mockNewsItems = [
  {
    id: "news1",
    title: "AI startups raise record $50B in Q1 2026 funding round",
    readers: 45800,
    timeAgo: "2h ago",
    category: "Technology",
  },
  {
    id: "news2",
    title: "Remote work reaches new high — 65% of tech workers fully remote",
    readers: 38200,
    timeAgo: "4h ago",
    category: "Work",
  },
  {
    id: "news3",
    title: "Tech layoffs reverse — companies resume aggressive hiring",
    readers: 29400,
    timeAgo: "6h ago",
    category: "Jobs",
  },
  {
    id: "news4",
    title: "OpenAI, Anthropic, Google compete for enterprise contracts worth $200B",
    readers: 22100,
    timeAgo: "8h ago",
    category: "AI",
  },
  {
    id: "news5",
    title: "Web3 developers shift to AI — 40% career change in past year",
    readers: 17600,
    timeAgo: "12h ago",
    category: "Development",
  },
];

export const suggestedConnections = mockUsers.filter(u => !u.isConnected).slice(0, 3);
